### ISSUE TITLE
Consistent treatment of ExceptionVisitor collection contents

### ISSUE THREAD

**Issue by CaptainEmerson** [brittjay0104/APATIANproto#20]
The contents of each Exception collection (e.g., throwStatements) should be added in the same way. Something like:

```
    public boolean visit(ThrowStatement node){

        add(node,
            signatureOfParent(node),
            throwStatements,
            ((ClassInstanceCreation)node.getExpression()).getType().toString());

        return true;
    }

    private String add(ASTNode node, String prefix, List<String> field, String clazz) {
        String src = findSourceForNode(node);
        String source = src.substring(0, src.indexOf("{"));
        String context = prefix + CHECK_SEPERATOR + source.trim();
        field.add(context);
        addExceptionKind(clazz, context);

        System.out.println(node.getClass().getName()+" found!");

        return context;
    }
```

This doesn't quite work for all collections, because there are some inconsistencies between the way things are inserted into the collections. For instance, sometimes CHECK_SEPERATOR is used, and sometimes it's not (e.g., not used for multiCatchBlocks). I'm unclear what the strings in these collections are supposed to mean, so I can't condense them myself.

**Comment by drbrittjay** [comment]
I can be more consistent but the goal is to make each thing collected unique so there is no risk of missing something because it is a duplicate string (i.e. had that problem with checked/unchecked exceptions because we added the same thing to both). And then there are things like type declarations where all you need to see if someone added it is the class signature. 

I try to make it more consistent across all but that might take some brainstorming on the best way to do that without compromising what goes on at the modelParser/modelRepo levels.
